### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by OrdinarySK** [amirmasoudabdol/amosa#1]
Hi, I am more interested in the AMOSA algorithm you wrote. I am now preparing to do a multi-objective optimization based on the AMOSA eco-hydrological site. But I am not very familiar with the C language, can you write it using R, python or Java?

**Comment by amirmasoudabdol** [comment]
I don't think that I have the time for that now; but if you are familiar with R, you can write your wrapper on top of the AMOSA using Rcpp library.
